flamebox/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$', 'flamebox.views.home', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^students/', include('students.urls', namespace="students"))
)

students/urls.py
from django.conf.urls import patterns, url

from students import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^(?P<student_id>\d+)/$', views.single, name='single'),
                       url(r'^result/(?P<student_id>\d+)$', views.result, name='result'),
                       )

students/models.py
from django.db import models

# Create your models here.


class Profile(models.Model):
    user_name = models.CharField(max_length=20)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    roll = models.IntegerField()

    def get_full_name(self):
        return self.first_name + " " + self.last_name

    def __str__(self):
        return self.user_name


class Result(models.Model):
    student = models.ForeignKey(Profile)
    exam_name = models.CharField(max_length=50)
    result = models.IntegerField()

    def __str__(self):
        return self.student.get_full_name()

flamebox/views.py
from django.shortcuts import render, get_object_or_404


def home(request):
    return render(request, 'flamebox/index.html', {'message': 'hello'})

students/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.


# importing models

from students.models import Profile


def index(request):
    students_list = Profile.objects.order_by('id')
    context = {
        'students_list': students_list
    }
    return render(request, 'students/index.html', context)


def single(request, student_id):
    profile = get_object_or_404(Profile, pk=student_id)
    return render(request, 'students/profile.html', {'profile': profile})


def result(request, student_id):
    return "Something"

templates/flamebox/index.html
Hi have a look at <a href="{% url 'students:index' %}">Students</a>

templates/students/index.html
{% if students_list %}
<ul>
    {% for student in students_list %}
    <li><a href="{% url 'students:single' student.id %}">{{ student.user_name }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No student are available.</p>
{% endif %}

templates/students/profile.html
<ul>
    <li>User Name : {{profile.user_name}}</li>
    <li>Full Name : {{profile.first_name}} {{profile.last_name}}</li>
    <li>Roll : {{profile.roll}}</li>
</ul>